### ISSUE TITLE
Random Disconnects

### ISSUE THREAD

**Issue by BIzZmarCk** [hexlo/terraria-server-docker#19]
I get random disconnects while playing on the server. Suddenly without any seeable reason.
All players get disconnected.
docker logs is empty.
Server (vm) seems to be running the whole time (teamspeak server is working during disconnect from terraria server).
world is reset back in time a few minutes. 
Must be a newer Issue because i had the server running with the same setup like 6 months ago and it worked flawlessly back than

**Comment by hexlo** [comment]
I haven't seen this before and haven't experienced it myself. Pretty hard to diagnose without more information. What happens to the container when the disconnects happen? Is the container still up or does it reset? Can you reconnect right after?

**Comment by BIzZmarCk** [comment]
i can reconnect right after the container restarts. i just had the container running attached and the container exited with code 137. after quick google research i looked into memory usage with docker stats. the memory usage keeps increasing but never reaches the allocated maximum of 31 gb it uses more like 1gb to 3gb.

**Comment by hexlo** [comment]
Are you using the amd64 or arm64 image?

Have you tried setting memory limits for the container? Here's a docker compose example you could try (add the `deploy:` section):

```
services:
  terraria-server:
    image: hexlo/terraria-server-docker:latest
    container_name: terraria-server
    deploy:
      resources:
        limits:
          memory: 4096M
    restart: unless-stopped
    ...
    
```

You can also check memory usage in real time using the command `docker stats`.
