### ISSUE TITLE
Run in Raspberry Pi 4?

### ISSUE THREAD

**Issue by FranciscoCross** [hexlo/terraria-server-docker#3]
Hello, I wanted to ask you if it can be run on a raspberry Pi 4 (arm)?
If so, how could I do it?
Thanks and regards

**Comment by hexlo** [comment]
Unfortunately, it cannot run on arm. I am using the vanilla server provided by re-logic, and there is only an X86 version. If they release an ARM version, I'd be happy to do so as well!

**Comment by FranciscoCross** [comment]
If I am currently running a ryshe image it works great on raspberry
Build a docker compose that uses an .env with name of the world to raise, very simple

I was looking to put mods
```

version: "3.8"

services:

  terraria:
    image: "ryshe/terraria:latest"
    build:
      context: ./
    container_name: terraria
    restart: always
    env_file:
      - .env
    volumes:
       - './terraria/world:/root/.local/share/Terraria/Worlds'
       - './terraria/world/ServerPlugins:/tshock/ServerPlugins'
    ports:
      - "7777:7777"
```
